from django.urls import path

from .views import (
    AddCommentView,
    AddStatusCommentView,
    ClarificationCommentRequestView,
    ClarificationInboxView,
    ClarificationMessageCreateView,
    ClarificationPostRequestView,
    ClarificationReactionView,
    ClarificationRespondView,
    CommunityUserProfileView,
    ConversationDetailView,
    DeletePrivateMessageView,
    ConversationInboxView,
    ConversationCallSignalView,
    ConversationCallInboxView,
    ConversationMessagesPollView,
    CreateGroupView,
    CreateGroupPageView,
    CreatePostView,
    CreateStatusPageView,
    CreateStatusView,
    DeleteCommentView,
    DeletePostView,
    GroupDetailView,
    GroupJoinRequestDecisionView,
    JoinGroupView,
    ModeratorDashboardView,
    NotificationsView,
    PostDetailView,
    PrivateConversationStartView,
    ReportCommentView,
    ReportPostView,
    ResolveReportView,
    ShareStatusView,
    SocialFeedView,
    StatusDetailView,
    ToggleCommentReactionView,
    ToggleLikeView,
    ToggleStatusLikeView,
)

app_name = 'chats'

urlpatterns = [
    path('', SocialFeedView.as_view(), name='feed'),
    path('groups/', SocialFeedView.as_view(), {'section': 'groups'}, name='feed_groups'),
    path('groups/add/', CreateGroupPageView.as_view(), name='group_add'),
    path('posts/', SocialFeedView.as_view(), {'section': 'posts'}, name='feed_posts'),
    path('status/', SocialFeedView.as_view(), {'section': 'status'}, name='feed_status'),
    path('private/', SocialFeedView.as_view(), {'section': 'private'}, name='feed_private'),
    path('notifications/', NotificationsView.as_view(), name='notifications'),
    path('inbox/', ConversationInboxView.as_view(), name='inbox'),
    path('profile/<int:user_id>/', CommunityUserProfileView.as_view(), name='user_profile'),
    path('doctor/<int:doctor_id>/start/', PrivateConversationStartView.as_view(), name='start_private_chat'),
    path('conversation/<int:conversation_id>/', ConversationDetailView.as_view(), name='conversation_detail'),
    path('conversation/<int:conversation_id>/poll/', ConversationMessagesPollView.as_view(), name='conversation_poll'),
    path('conversation/<int:conversation_id>/call/signal/', ConversationCallSignalView.as_view(), name='conversation_call_signal'),
    path('call/inbox/', ConversationCallInboxView.as_view(), name='conversation_call_inbox'),
    path('conversation/<int:conversation_id>/message/<int:message_id>/delete/', DeletePrivateMessageView.as_view(), name='conversation_delete_message'),
    path('moderation/', ModeratorDashboardView.as_view(), name='moderator_dashboard'),
    path('clarifications/', ClarificationInboxView.as_view(), name='clarification_inbox'),
    path('clarifications/<int:clarification_id>/respond/', ClarificationRespondView.as_view(), name='clarification_respond'),
    path('clarifications/<int:clarification_id>/reply/', ClarificationMessageCreateView.as_view(), name='clarification_reply'),
    path('clarifications/<int:clarification_id>/react/<str:reaction>/', ClarificationReactionView.as_view(), name='clarification_react'),
    path('report/<int:report_id>/resolve/', ResolveReportView.as_view(), name='report_resolve'),
    path('groups/create/', CreateGroupView.as_view(), name='group_create'),
    path('groups/<int:group_id>/join/', JoinGroupView.as_view(), name='group_join'),
    path('groups/<int:group_id>/', GroupDetailView.as_view(), name='group_detail'),
    path('groups/join-request/<int:request_id>/decision/', GroupJoinRequestDecisionView.as_view(), name='group_join_request_decision'),
    path('status/create/', CreateStatusView.as_view(), name='status_create'),
    path('status/new/', CreateStatusPageView.as_view(), name='status_new'),
    path('status/<int:status_id>/', StatusDetailView.as_view(), name='status_detail'),
    path('status/<int:status_id>/like/', ToggleStatusLikeView.as_view(), name='status_like'),
    path('status/<int:status_id>/comment/', AddStatusCommentView.as_view(), name='status_comment'),
    path('status/<int:status_id>/share/', ShareStatusView.as_view(), name='status_share'),
    path('post/create/', CreatePostView.as_view(), name='post_create'),
    path('post/<int:post_id>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<int:post_id>/like/', ToggleLikeView.as_view(), name='post_like'),
    path('post/<int:post_id>/comment/', AddCommentView.as_view(), name='post_comment'),
    path('post/<int:post_id>/clarify/', ClarificationPostRequestView.as_view(), name='post_clarify'),
    path('post/<int:post_id>/report/', ReportPostView.as_view(), name='post_report'),
    path('post/<int:post_id>/delete/', DeletePostView.as_view(), name='post_delete'),
    path('comment/<int:comment_id>/react/<str:reaction>/', ToggleCommentReactionView.as_view(), name='comment_react'),
    path('comment/<int:comment_id>/clarify/', ClarificationCommentRequestView.as_view(), name='comment_clarify'),
    path('comment/<int:comment_id>/report/', ReportCommentView.as_view(), name='comment_report'),
    path('comment/<int:comment_id>/delete/', DeleteCommentView.as_view(), name='comment_delete'),
]
