# Generated by Django 6.0.4 on 2026-04-08 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAIPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('health_notes', models.TextField(blank=True, help_text='General health information')),
                ('permanent_diseases', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('lifestyle_notes', models.TextField(blank=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('stress_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('exercise_frequency', models.CharField(blank=True, choices=[('none', 'No regular exercise'), ('light', 'Light 1-2x/week'), ('moderate', 'Moderate 3-4x/week'), ('high', 'High 5x+/week')], max_length=20)),
                ('diet', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('mental_health', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('location_region', models.CharField(blank=True, max_length=120)),
                ('language_preference', models.CharField(default='sw', max_length=30)),
                ('ai_data_consent', models.BooleanField(default=True)),
                ('identity_verified', models.BooleanField(default=False)),
                ('medical_info_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('last_data_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completeness_score', models.PositiveSmallIntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_persona', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('profile_update', 'Profile update'), ('periodic', 'Periodic capture')], default='profile_update', max_length=20)),
                ('completeness_score', models.PositiveSmallIntegerField(default=0)),
                ('identity_verified', models.BooleanField(default=False)),
                ('medical_info_verified', models.BooleanField(default=False)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_snapshots', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='users.useraipersona')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
