# Generated by Django 6.0.3 on 2026-03-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraipersona',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='useraipersona',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
