# Generated by Django 6.0.3 on 2026-04-01 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraipersona_avatar_useraipersona_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useraipersona',
            name='ai_data_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraipersona',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='useraipersona',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='useraipersona',
            name='identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraipersona',
            name='language_preference',
            field=models.CharField(default='sw', max_length=30),
        ),
        migrations.AddField(
            model_name='useraipersona',
            name='last_data_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraipersona',
            name='location_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='useraipersona',
            name='medical_info_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraipersona',
            name='profile_completeness_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraipersona',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PersonaDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('profile_update', 'Profile update'), ('periodic', 'Periodic capture')], default='profile_update', max_length=20)),
                ('completeness_score', models.PositiveSmallIntegerField(default=0)),
                ('identity_verified', models.BooleanField(default=False)),
                ('medical_info_verified', models.BooleanField(default=False)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='users.useraipersona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
