# Generated by Django 6.0.3 on 2026-04-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraipersona_ai_data_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraipersona',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
