# Generated by Django 6.0.4 on 2026-04-08 00:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PubertyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('age_group', models.CharField(blank=True, max_length=32, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='puberty/guides/')),
            ],
        ),
        migrations.CreateModel(
            name='PubertyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('mental_health', 'Mental Health'), ('hygiene', 'Hygiene'), ('menstrual', 'Menstrual'), ('body_change', 'Body Change'), ('voice_change', 'Voice Change'), ('emotional', 'Emotional'), ('cultural', 'Cultural')], max_length=32)),
                ('gender_specific', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('age_group', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PubertyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('mental_health', 'Mental Health'), ('hygiene', 'Hygiene'), ('menstrual', 'Menstrual'), ('body_change', 'Body Change'), ('voice_change', 'Voice Change'), ('emotional', 'Emotional'), ('cultural', 'Cultural')], max_length=32)),
                ('priority', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PubertyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('puberty_stage', models.CharField(max_length=50)),
                ('concerns', models.JSONField(blank=True, default=dict)),
                ('country', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puberty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PubertyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puberty.pubertyquestion')),
            ],
        ),
    ]
