# Generated by Django 6.0.4 on 2026-04-08 00:11

import django.db.models.deletion
import django.utils.timezone
import menstrual.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_groups/')),
                ('audience_gender', models.CharField(choices=[('female', 'Female community'), ('male', 'Male community')], default='female', max_length=10)),
                ('require_join_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_community_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='community_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'audience_gender')},
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name="What's on your mind?")),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_posts/')),
                ('video', models.FileField(blank=True, null=True, upload_to='community_posts/videos/')),
                ('media_ratio', models.CharField(default='auto', max_length=20)),
                ('media_shape', models.CharField(default='rounded', max_length=20)),
                ('media_focus_x', models.PositiveSmallIntegerField(default=50)),
                ('media_focus_y', models.PositiveSmallIntegerField(default=50)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('audience_gender', models.CharField(choices=[('female', 'Female community'), ('male', 'Male community')], default='female', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='menstrual.communitygroup')),
                ('groups', models.ManyToManyField(blank=True, related_name='multi_posts', to='menstrual.communitygroup')),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_posts/multi/')),
                ('video', models.FileField(blank=True, null=True, upload_to='community_posts/videos/multi/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='menstrual.communitypost')),
            ],
            options={
                'ordering': ['sort_order', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='menstrual.communityreply')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='menstrual.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_gender', models.CharField(choices=[('female', 'Female community'), ('male', 'Male community')], default='female', max_length=10)),
                ('content', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_status/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=menstrual.models.default_status_expiry)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='menstrual.communitygroup')),
                ('likes', models.ManyToManyField(blank=True, related_name='community_status_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityStatusComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='menstrual.communitystatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_status_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityStatusMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_status/multi/')),
                ('video', models.FileField(blank=True, null=True, upload_to='community_status/videos/multi/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='menstrual.communitystatus')),
            ],
            options={
                'ordering': ['sort_order', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tip Header')),
                ('content', models.TextField(verbose_name='Tip Content')),
                ('source', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DOCTOR', 'Professional Doctor'), ('WEB', 'Verified Website')], default='AI', max_length=10)),
                ('url', models.URLField(blank=True, help_text='Source URL link', null=True)),
                ('ui_structure', models.JSONField(default=dict, help_text='AI generated CSS/Visual structure')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('saved_permanent', models.ManyToManyField(blank=True, related_name='permanent_tips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10)),
                ('specialization', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Siku ya kwanza ya kuanza mzunguko', verbose_name='Start Date')),
                ('expected_end_date', models.DateField(help_text='Siku inayotarajiwa kuisha', verbose_name='Expected End Date')),
                ('cycle_length', models.PositiveSmallIntegerField(default=28, help_text='Urefu wa mzunguko (siku), mfano 28')),
                ('period_duration', models.PositiveSmallIntegerField(default=5, help_text='Muda wa hedhi kwa siku, mfano 5')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenstrualUserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_mode', models.BooleanField(default=True, help_text='Hide sensitive details on dashboard')),
                ('anonymous_mode', models.BooleanField(default=False, help_text='Post to community anonymously by default')),
                ('emergency_alerts_enabled', models.BooleanField(default=True)),
                ('reminder_period', models.BooleanField(default=True)),
                ('reminder_ovulation', models.BooleanField(default=True)),
                ('reminder_fertile_window', models.BooleanField(default=True)),
                ('color_theme', models.CharField(choices=[('default', 'Default Green'), ('gold', 'Gold'), ('rose', 'Rose'), ('ocean', 'Ocean'), ('lavender', 'Lavender')], default='default', max_length=20)),
                ('use_custom_palette', models.BooleanField(default=False)),
                ('custom_primary', models.CharField(default='#2F6B3F', max_length=7)),
                ('custom_secondary', models.CharField(default='#7FB77E', max_length=7)),
                ('background_style', models.CharField(choices=[('solid', 'Solid'), ('linear', 'Linear Gradient'), ('radial', 'Radial Gradient')], default='linear', max_length=20)),
                ('background_intensity', models.PositiveSmallIntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menstrual_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityGroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.CharField(blank=True, max_length=220)),
                ('is_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='menstrual.communitygroup')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_group_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_group_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommunityStatusShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='menstrual.communitystatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_status_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('status', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('flow_intensity', models.IntegerField(default=0, help_text='Weka kiwango cha damu (1-5)')),
                ('flow_notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Flow Notes')),
                ('physical_symptoms', models.JSONField(default=list, help_text='Cramps, bloating, headaches, etc.')),
                ('emotional_changes', models.JSONField(default=list, help_text='Mood swings, anxiety, etc.')),
                ('sleep_patterns', models.JSONField(default=list, help_text='Trouble sleeping or tired')),
                ('ai_suggestion', models.TextField(blank=True, null=True, verbose_name='AI Suggestions')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='menstrual.menstrualcycle')),
            ],
            options={
                'unique_together': {('cycle', 'date')},
            },
        ),
    ]
