# Generated by Django 6.0.3 on 2026-03-27 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name="What's on your mind?")),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='menstrual.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tip Header')),
                ('content', models.TextField(verbose_name='Tip Content')),
                ('source', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DOCTOR', 'Professional Doctor'), ('WEB', 'Verified Website')], default='AI', max_length=10)),
                ('url', models.URLField(blank=True, help_text='Source URL link', null=True)),
                ('ui_structure', models.JSONField(default=dict, help_text='AI generated CSS/Visual structure')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('saved_permanent', models.ManyToManyField(blank=True, related_name='permanent_tips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Siku ya kwanza ya kuanza mzunguko', verbose_name='Start Date')),
                ('expected_end_date', models.DateField(help_text='Siku inayotarajiwa kuisha', verbose_name='Expected End Date')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('flow_intensity', models.IntegerField(default=0, help_text='Weka kiwango cha damu (1-5)')),
                ('flow_notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Flow Notes')),
                ('physical_symptoms', models.JSONField(default=list, help_text='Cramps, bloating, headaches, etc.')),
                ('emotional_changes', models.JSONField(default=list, help_text='Mood swings, anxiety, etc.')),
                ('sleep_patterns', models.JSONField(default=list, help_text='Trouble sleeping or tired')),
                ('ai_suggestion', models.TextField(blank=True, null=True, verbose_name='AI Suggestions')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='menstrual.menstrualcycle')),
            ],
            options={
                'unique_together': {('cycle', 'date')},
            },
        ),
    ]
