# Generated by Django 6.0.3 on 2026-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menstrual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menstrualcycle',
            name='cycle_length',
            field=models.PositiveSmallIntegerField(default=28, help_text='Urefu wa mzunguko (siku), mfano 28'),
        ),
        migrations.AddField(
            model_name='menstrualcycle',
            name='period_duration',
            field=models.PositiveSmallIntegerField(default=5, help_text='Muda wa hedhi kwa siku, mfano 5'),
        ),
    ]
