# Generated by Django 6.0.3 on 2026-03-30 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menstrual', '0002_menstrualcycle_cycle_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenstrualUserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_mode', models.BooleanField(default=True, help_text='Hide sensitive details on dashboard')),
                ('emergency_alerts_enabled', models.BooleanField(default=True)),
                ('reminder_period', models.BooleanField(default=True)),
                ('reminder_ovulation', models.BooleanField(default=True)),
                ('reminder_fertile_window', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menstrual_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
