# Generated by Django 6.0.3 on 2026-04-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menstrual', '0002_community_media_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
