# Generated by Django 6.0.3 on 2026-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menstrual', '0003_menstrualusersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menstrualusersetting',
            name='anonymous_mode',
            field=models.BooleanField(default=False, help_text='Post to community anonymously by default'),
        ),
    ]
