# Generated by Django 6.0.3 on 2026-03-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menstrual', '0004_communitypost_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='audience_gender',
            field=models.CharField(choices=[('female', 'Female community'), ('male', 'Male community')], default='female', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10),
        ),
    ]
