# Generated by Django 6.0.3 on 2026-03-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menstrual', '0007_communitypost_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='media_focus_x',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='media_focus_y',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='media_ratio',
            field=models.CharField(default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='media_shape',
            field=models.CharField(default='rounded', max_length=20),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community_posts/videos/'),
        ),
    ]
