# Generated by Django 6.0.3 on 2026-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menstrual', '0008_communitypost_media_focus_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menstrualusersetting',
            name='color_theme',
            field=models.CharField(choices=[('default', 'Default Green'), ('gold', 'Gold'), ('rose', 'Rose'), ('ocean', 'Ocean'), ('lavender', 'Lavender')], default='default', max_length=20),
        ),
    ]
