# Generated by Django 6.0.3 on 2026-04-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menstrual', '0009_menstrualusersetting_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='menstrualusersetting',
            name='background_intensity',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='menstrualusersetting',
            name='background_style',
            field=models.CharField(choices=[('solid', 'Solid'), ('linear', 'Linear Gradient'), ('radial', 'Radial Gradient')], default='linear', max_length=20),
        ),
        migrations.AddField(
            model_name='menstrualusersetting',
            name='custom_primary',
            field=models.CharField(default='#2F6B3F', max_length=7),
        ),
        migrations.AddField(
            model_name='menstrualusersetting',
            name='custom_secondary',
            field=models.CharField(default='#7FB77E', max_length=7),
        ),
        migrations.AddField(
            model_name='menstrualusersetting',
            name='use_custom_palette',
            field=models.BooleanField(default=False),
        ),
    ]
