# Generated by Django 6.0.4 on 2026-04-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('active_ingredients', models.TextField(blank=True)),
                ('rx_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanism', models.TextField(blank=True, help_text='Jinsi dawa inavyofanya kazi', null=True)),
                ('side_effects', models.JSONField(blank=True, help_text='Orodha ya madhara ya kawaida', null=True)),
                ('faqs', models.JSONField(blank=True, help_text='Maswali na majibu (Q&A)', null=True)),
                ('doctor_advice', models.TextField(blank=True, help_text='Ushauri wa daktari', null=True)),
                ('did_you_know', models.TextField(blank=True, help_text='Fact ya haraka kuhusu dawa', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
