# Generated by Django 6.0.3 on 2026-04-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='did_you_know',
            field=models.TextField(blank=True, help_text='Fact ya haraka kuhusu dawa', null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='doctor_advice',
            field=models.TextField(blank=True, help_text='Ushauri wa daktari', null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='faqs',
            field=models.JSONField(blank=True, help_text='Maswali na majibu (Q&A)', null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='mechanism',
            field=models.TextField(blank=True, help_text='Jinsi dawa inavyofanya kazi', null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects',
            field=models.JSONField(blank=True, help_text='Orodha ya madhara ya kawaida', null=True),
        ),
    ]
