# Generated by Django 6.0.3 on 2026-03-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=40)),
                ('message_text', models.TextField(blank=True)),
                ('reply_text', models.TextField(blank=True)),
                ('outbound_sent', models.BooleanField(default=False)),
                ('outbound_detail', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
