# Generated by Django 6.0.3 on 2026-04-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('icd_code', models.CharField(blank=True, max_length=100)),
                ('definition', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
