# Generated by Django 6.0.4 on 2026-04-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('icd_code', models.CharField(blank=True, max_length=100)),
                ('definition', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complications', models.JSONField(blank=True, help_text='Orodha ya madhara/matatizo yanayoweza kutokea', null=True)),
                ('faqs', models.JSONField(blank=True, help_text='Maswali na majibu (Q&A)', null=True)),
                ('doctor_advice', models.TextField(blank=True, help_text='Ushauri wa daktari', null=True)),
                ('did_you_know', models.TextField(blank=True, help_text='Fact ya haraka kuhusu ugonjwa', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
