# Generated by Django 6.0.4 on 2026-04-12 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={},
        ),
        migrations.RemoveField(
            model_name='disease',
            name='complications',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='did_you_know',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='doctor_advice',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='faqs',
        ),
        migrations.AddField(
            model_name='disease',
            name='body_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='disease',
            name='is_chronic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disease',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='icd_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='treatment',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='UserDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(help_text="In case the disease isn't in our library", max_length=255)),
                ('diagnosis_date', models.DateField(default=django.utils.timezone.now)),
                ('severity_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9'), (10, 'Level 10')], default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('controlled', 'Under Control'), ('recovered', 'Recovered'), ('monitoring', 'Monitoring')], default='active', max_length=20)),
                ('is_chronic', models.BooleanField(default=False)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('last_ai_insight', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diseases.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diseases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice a day', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='diseases.userdisease')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('symptoms_noted', models.TextField(help_text='Describe how you feel today')),
                ('severity_score', models.IntegerField(default=1)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('oxygen_level', models.IntegerField(blank=True, null=True)),
                ('blood_sugar', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, max_length=100)),
                ('energy_level', models.IntegerField(default=5)),
                ('sleep_hours', models.FloatField(default=8.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='diseases.userdisease')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user_disease', 'date')},
            },
        ),
    ]
