# Generated by Django 6.0.3 on 2026-04-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='complications',
            field=models.JSONField(blank=True, help_text='Orodha ya madhara/matatizo yanayoweza kutokea', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='did_you_know',
            field=models.TextField(blank=True, help_text='Fact ya haraka kuhusu ugonjwa', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='doctor_advice',
            field=models.TextField(blank=True, help_text='Ushauri wa daktari', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='faqs',
            field=models.JSONField(blank=True, help_text='Maswali na majibu (Q&A)', null=True),
        ),
    ]
