# Generated by Django 6.0.4 on 2026-04-12 22:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_alter_disease_created_at_alter_disease_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('taken', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_logs', to='diseases.diseasemedication')),
            ],
            options={
                'unique_together': {('medication', 'date')},
            },
        ),
    ]
