# Generated by Django 6.0.3 on 2026-04-01 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('persona_update', 'Persona Update Reminder'), ('card_updated', 'Card Updated')], max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name_override', models.CharField(blank=True, max_length=150)),
                ('gender_override', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='health_cards/photos/')),
                ('show_name', models.BooleanField(default=True)),
                ('show_gender', models.BooleanField(default=True)),
                ('show_birth_date', models.BooleanField(default=True)),
                ('show_age', models.BooleanField(default=True)),
                ('show_health_notes', models.BooleanField(default=False)),
                ('show_permanent_diseases', models.BooleanField(default=False)),
                ('show_medications', models.BooleanField(default=False)),
                ('show_goals', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaReminderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveSmallIntegerField(default=30)),
                ('reminder_cooldown_days', models.PositiveSmallIntegerField(default=7)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_reminder_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
