# Generated by Django 6.0.3 on 2026-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='show_watermark',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='style_theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('aurora', 'Aurora'), ('midnight', 'Midnight'), ('emerald', 'Emerald')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='watermark_text',
            field=models.CharField(blank=True, default='afya-AI', max_length=80),
        ),
    ]
