# Generated by Django 6.0.3 on 2026-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_healthcard_show_watermark_healthcard_style_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='show_ai_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='show_lifestyle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='show_menstrual_chart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='show_menstrual_logs',
            field=models.BooleanField(default=False),
        ),
    ]
