# Generated by Django 6.0.3 on 2026-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_healthcard_show_ai_summary_healthcard_show_lifestyle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='public_access_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
