# Generated by Django 6.0.3 on 2026-04-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_healthcard_public_access_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='watermark_text',
            field=models.CharField(blank=True, default='AfyaSmart', max_length=80),
        ),
    ]
