# Generated by Django 6.0.3 on 2026-04-03 23:03

import random
import string
from django.db import migrations, models


def _make_number():
    chars = string.ascii_uppercase + string.digits
    segs = [''.join(random.choices(chars, k=4)) for _ in range(3)]
    return f"AFYA-{'-'.join(segs)}"


def populate_card_numbers(apps, schema_editor):
    HealthCard = apps.get_model('card', 'HealthCard')
    used = set()
    for card in HealthCard.objects.all():
        num = _make_number()
        while num in used:
            num = _make_number()
        used.add(num)
        card.card_number = num
        card.save(update_fields=['card_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_healthcard_watermark_text'),
    ]

    operations = [
        # Step 1: add without unique constraint so all rows can get empty first
        migrations.AddField(
            model_name='healthcard',
            name='card_number',
            field=models.CharField(blank=True, editable=False, max_length=20, default=''),
            preserve_default=False,
        ),
        # Step 2: fill in unique numbers for every existing row
        migrations.RunPython(populate_card_numbers, migrations.RunPython.noop),
        # Step 3: now enforce uniqueness
        migrations.AlterField(
            model_name='healthcard',
            name='card_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
