# Generated by Django 6.0.3 on 2026-04-01 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubertycheckrecord',
            name='red_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PubertyPreventionPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('action', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevention_plan_days', to='reproduction.pubertycheckrecord')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('check_record', 'day_number')},
            },
        ),
    ]
