# Generated by Django 6.0.3 on 2026-04-02 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_clarificationmessage_and_reactions'),
        ('menstrual', '0011_communitygroup_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clarificationrequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='menstrual.communitygroup'),
        ),
        migrations.AlterField(
            model_name='clarificationrequest',
            name='target_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('group_admin', 'Group Admin')], default='doctor', max_length=20),
        ),
    ]
