import json
from pathlib import Path

from django.conf import settings
from django.core.management import BaseCommand, call_command


HEADER_BY_LANG = {
    'en': [
        '# Generated by sync_unified_translations\n',
        'msgid ""\n',
        'msgstr ""\n',
        '"Project-Id-Version: afya-smart\\n"\n',
        '"Language: en\\n"\n',
        '"MIME-Version: 1.0\\n"\n',
        '"Content-Type: text/plain; charset=UTF-8\\n"\n',
        '"Content-Transfer-Encoding: 8bit\\n"\n',
        '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n',
        '\n',
    ],
    'ar': [
        '# Generated by sync_unified_translations\n',
        'msgid ""\n',
        'msgstr ""\n',
        '"Project-Id-Version: afya-smart\\n"\n',
        '"Language: ar\\n"\n',
        '"MIME-Version: 1.0\\n"\n',
        '"Content-Type: text/plain; charset=UTF-8\\n"\n',
        '"Content-Transfer-Encoding: 8bit\\n"\n',
        '"Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;\\n"\n',
        '\n',
    ],
}


def _po_escape(value: str) -> str:
    return value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


def _extract_msgids(po_text: str) -> list[str]:
    msgids: list[str] = []
    lines = po_text.splitlines()
    i = 0

    while i < len(lines):
        line = lines[i]
        if not line.startswith('msgid '):
            i += 1
            continue

        current = line[len('msgid '):].strip()
        chunks: list[str] = []
        if current.startswith('"') and current.endswith('"'):
            chunks.append(current[1:-1])

        i += 1
        while i < len(lines):
            next_line = lines[i].strip()
            if next_line.startswith('"') and next_line.endswith('"'):
                chunks.append(next_line[1:-1])
                i += 1
                continue
            break

        msgid = ''.join(chunks)
        if msgid:
            msgids.append(msgid)

    deduped: list[str] = []
    seen = set()
    for msgid in msgids:
        if msgid in seen:
            continue
        seen.add(msgid)
        deduped.append(msgid)
    return deduped


class Command(BaseCommand):
    help = 'Build en/ar locale files from a single catalog: locale/unified_translations.json'

    def handle(self, *args, **options):
        base_dir = Path(settings.BASE_DIR)
        locale_dir = base_dir / 'locale'
        source_po = locale_dir / 'sw' / 'LC_MESSAGES' / 'django.po'
        catalog_path = locale_dir / 'unified_translations.json'

        if not source_po.exists():
            self.stderr.write(self.style.ERROR(f'Source file not found: {source_po}'))
            return

        if not catalog_path.exists():
            self.stderr.write(self.style.ERROR(f'Catalog file not found: {catalog_path}'))
            return

        try:
            catalog = json.loads(catalog_path.read_text(encoding='utf-8'))
        except json.JSONDecodeError as exc:
            self.stderr.write(self.style.ERROR(f'Invalid JSON in {catalog_path}: {exc}'))
            return

        src_text = source_po.read_text(encoding='utf-8')
        msgids = _extract_msgids(src_text)

        en_map = catalog.get('en', {})
        ar_map = catalog.get('ar', {})

        for lang_code in ('en', 'ar'):
            target_dir = locale_dir / lang_code / 'LC_MESSAGES'
            target_dir.mkdir(parents=True, exist_ok=True)
            target_po = target_dir / 'django.po'

            out_lines = list(HEADER_BY_LANG[lang_code])

            for msgid in msgids:
                en_value = en_map.get(msgid, msgid)
                if lang_code == 'en':
                    translated = en_value
                else:
                    translated = ar_map.get(msgid, ar_map.get(en_value, en_value))

                out_lines.append(f'msgid "{_po_escape(msgid)}"\n')
                out_lines.append(f'msgstr "{_po_escape(translated)}"\n')
                out_lines.append('\n')

            target_po.write_text(''.join(out_lines), encoding='utf-8')
            self.stdout.write(self.style.SUCCESS(f'Updated {target_po}'))

        call_command('compilemessages', locale=['en', 'ar'], ignore=['venv', '*.pyc'])
        self.stdout.write(self.style.SUCCESS('Compiled translations successfully.'))
