# Generated by Django 6.0.3 on 2026-04-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_rating_report_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlogfield',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Kwa select: orodha ya chaguzi, kwa mfano ["Ndiyo","Hapana"]'),
        ),
    ]
